version: "3.9"
services:
  base:
    build:
      context: . 
      dockerfile: Dockerfile
      args:
        working_dir: "/docker"
    environment: 
      WORKING_DIR: "/docker"
  dev:
    ports:
      - "3000:3000"
    volumes:
      - .:/docker
    extends:
      service: base
    environment:
      APP_NAME: jupioca
    command: >
        sh -c "
          cd src/app
          yarn next
        "

