version: "3.9"
services:
  base:
    build:
      context: . 
      dockerfile: Dockerfile
      args:
        working_dir: "/docker"
    environment: 
      WORKING_DIR: "/docker"
  next:
    ports:
      - "3000:3000"
    volumes:
      - .:/docker
    extends:
      service: base
    environment:
      APP_NAME: nextjs
    command: >
        sh -c "
          cd src/app
          yarn dev
        "
  build:
    volumes:
      - .:/docker
    extends:
      service: base
    environment:
      APP_NAME: nextjs
    command: >
        sh -c "
          cd src/app
          yarn build
        "

  start:
    ports:
      - "3000:3000"
    volumes:
      - .:/docker
    extends:
      service: base
    environment:
      APP_NAME: nextjs
    command: >
        sh -c "
          cd src/app
          yarn build
        "
  export:
    volumes:
      - .:/docker
    extends:
      service: base
    environment:
      APP_NAME: nextjs
    command: >
        sh -c "
          cd src/app
          yarn export
        "
  build-css:
    ports:
      - "3000:3000"
    volumes:
      - .:/docker
    extends:
      service: base
    environment:
      APP_NAME: nextjs
    command: >
        sh -c "
          cd src/app/static
          yarn
          ./node_modules/gulp/bin/gulp.js watch
        "